todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todolist.urls")),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "todolist"

urlpatterns = [
    path('', views.home, name="home_page"),
    path('todo/', views.index, name="index_page"),
    path('todo/<int:list_id>',views.list, name="list_page"),
    path('update/<int:list_id>',views.update_item, name="update_item_page"),
    path('test/<int:list_id>',views.test_item, name="test_page"),
]

todolist/models.py
from django.db import models
from datetime import datetime, timezone
from django.utils.timezone import localtime, now
import pytz

# Create your models here.


class TodoList(models.Model):
    title = models.CharField(max_length=120)
    completed = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    # def update_completed(self):
    #     '''returns number of completed items, total number of items'''
    #     items = TodoItem.objects.all()
    #     list=items.list(id=self.id)
    #     self.completed = 0
    #     counter = 0
    #     for i in items:
    #         counter += 1
    #         if i.done is True:
    #             self.completed += 1
    #     return self.completed/counter


class TodoItem(models.Model):
    list = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField()
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.name
        # if len(self.name) <= 10:
        #     return self.name
        # else:
        #     return f"{self.name[:10]}..."


    def days_left(self):
        '''Calculate how many days left before this item is due, or a warning string'''
        # now = datetime.now()
        # # dd/mm/YY H:M:S
        # dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
        today = localtime(now())
        delta = (self.due_date - today)
        if delta.days > 0:
            return delta.days
        elif delta.days == 0:
            return f"Due today!"

        else:
            return "Overdue!!!"

todolist/forms.py
from django import forms
from .models import TodoItem,TodoList


class UpdateItems(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ["done"]

class UpdateList(forms.ModelForm):
    class Meta:
        model=TodoList
        fields=["completed"]

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoList,TodoItem
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import UpdateItems, UpdateList
from django.contrib import messages

# Create your views here.


def home(request):
    # context={"dummy": [{"list": 'dfads'}]}
    return render(request, "todolist/home.html")


def index(request):
    todo=TodoList.objects.order_by("title")
    lists={}
    for l in todo:
        items = l.todoitem_set.all()
        n = 0
        total =0
        for item in items:
            total += 1
            if item.done is True:
                n += 1
        lists[l] = n/total
    context = {"lists": lists}
    return render(request, "todolist/index.html", context)


def list(request, list_id):
    todo = TodoList.objects.get(id=list_id)
    num_completed = todo.completed
    print(num_completed)
    print(request.POST.getlist("done"))
    for i in request.POST.getlist("done"):
        todoitem=todo.todoitem_set.get(id=i)
        todoitem.done=True
        todoitem.save()
        num_completed += 1
    todo.completed = num_completed
    todo.save()

    context = {"list":todo}
    return render(request, 'todolist/todo.html', context)


def update_item(request, list_id):
    list_content = TodoList.objects.get(id=list_id)
    items=TodoItem.objects.filter(list=list_id)
    # print(request.POST)
    context = {"list": list_content, "items":items, "listid":list_id}
    return render(request, 'todolist/update_item.html', context)


def test_item(request, list_id):
    todo = TodoList.objects.get(id=list_id)
    num_completed = todo.completed
    print(num_completed)
    print(request.POST.getlist("done"))
    for i in request.POST.getlist("done"):
        todoitem=todo.todoitem_set.get(id=i)
        todoitem.done=True
        todoitem.save()
        num_completed += 1
    todo.completed = num_completed
    todo.save()

    context = {"list":todo}
    return render(request, 'todolist/test.html', context)

todolist/templates/todolist/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
            <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'todolist/main.css' %}">

    <title>Todo list</title>
</head>
<body>
      <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'todolist:index_page' %}">To-do List</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{% url 'todolist:index_page' %}">Index</a>
                  <a class="nav-item nav-link" href="#">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  <a class="nav-item nav-link" href="#">Login</a>
                  <a class="nav-item nav-link" href="#">Register</a>
                </div>
              </div>
            </div>
          </nav>
        </header>

   <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% block content %}

            {% endblock %}
        </div>
        <div class="col-md-4">
          <!--<div class="content-section">-->
            <!--<h3>Our Sidebar</h3>-->
            <!--<p class='text-muted'>You can put any information here you'd like.-->
              <!--<ul class="list-group">-->
                <!--<li class="list-group-item list-group-item-light">Latest Posts</li>-->
                <!--<li class="list-group-item list-group-item-light">Announcements</li>-->
                <!--<li class="list-group-item list-group-item-light">Calendars</li>-->
                <!--<li class="list-group-item list-group-item-light">etc</li>-->
              <!--</ul>-->
            <!--</p>-->
          <!--</div>-->
        </div>
      </div>
       <br>

       <foot>copyright @2019 Mingy</foot>
    </main>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

todolist/templates/todolist/home.html
{% extends "todolist/base.html" %}

{% block content %}
    <h1>This is the HOME page</h1>
{% endblock content %}

todolist/templates/todolist/index.html
{% extends "todolist/base.html" %}

{% block content %}
    <h3>The Overview:</h3>

    <br>
    <div class="row">
      <div class="col-sm-8">
        <ol>
            {% for list, num in lists.items %}
                <li>
                    <a href="{% url 'todolist:list_page' list.id%}"><strong>{{list}}</strong></a>

                </li>
                <br>
            {% endfor %}
        </ol>
      </div>
      <div class="col-sm-2">
        <ul style="list-style-type:none;">
            {% for list, num in lists.items %}
                <li>
                    {% if num == 0 %}
                        <button class="btn danger">Nothing's done</button>
                    {%elif num == 1 %}
                        <button class="btn success">All done</button>
                    {% else %}
                        <button class="btn warning">Almost there: {% widthratio num 1 100 %}% done</button>
                    {% endif%}
                </li>
            <br>
            {% endfor %}
        </ul>
      </div>
    </div>

{% endblock content %}

todolist/templates/todolist/test.html
{% extends "todolist/base.html" %}

{% block content %}
{% for item in list.todoitem_set.all %}
{% if item.done is False %}
<p>0. {{item.name}}  is not done</p>
{% else %}
<p>1. {{item.name}} is done</p>
{% endif %}
{% endfor %}


<h1>{{ list.title }}: {{list.completed}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'todolist:test_page' list.id %}" method="post">
{% csrf_token %}
{% for item in list.todoitem_set.all %}
    <input type="checkbox" name="done" id="item{{ forloop.counter }}" value="{{ item.id }}">
    <label for="item{{ forloop.counter }}">{{item.name}}</label><br>
{% endfor %}
<input type="submit" value="update my list">
</form>


{% endblock content %}

todolist/templates/todolist/todo.html
{% extends "todolist/base.html" %}

{% block content %}
    <h3>Here is what you have to do:</h3>
    <br>
    <p><h4>{{list}}: ({{list.completed}} completed)</h4></p>
    <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'todolist:list_page' list.id %}" method='post'>
    {% csrf_token%}
    <ol>
        {% for item in list.todoitem_set.all %}
            <li>
                <h5>{{item.name}}</h5>

                <div class="row">
                      <div class="col-sm-2">
                          {% if item.done is False%}
                              <label class="checkbox-inline">Done:</label >
                                  <input type="checkbox" name="done" id="item{{ forloop.counter }}" value="{{ item.id }}" data-toggle="toggle">
                          {% else %}
                              <label class="checkbox-inline">Done:</label>
                                  <input type="checkbox" checked disabled data-toggle="toggle">

                          {% endif %}
                      </div>
                      <div class="col-sm-6">
                          {% if item.done is True%}
                            {{item.description}}
                          {% else %}
                            {{item.description}}
                          {% endif %}
                      </div>

                      <div class="col-sm-4">
                          {% if item.done is True %}
                            <p style="background-color:LightGray;">Status: It's done! </p>
                          {% elif item.days_left == "Overdue!!!" %}
                            <p style="background-color:Tomato;">Status: {{item.days_left}}</p>
                          {% elif item.days_left == "Due today!" %}
                            <p style="background-color:Orange;">Status: {{item.days_left}}</p>
                          {% else %}
                            <p>Status: {{item.days_left}} days left</p>
                          {% endif%}
                      </div>
                </div>
            </li>
        {% endfor %}
    </ol>

    <input type="submit" value="Update my list">
    </form>


{% endblock content %}

todolist/templates/todolist/update_item.html
{% extends "todolist/base.html" %}

{% block content %}
    <h3>Here is what you have to do:</h3>
    <br>
    <p><h4>{{list}} ({{list.completed}} completed)</h4></p>
    <br>


    <ol>
        {% for item in items %}
            <li>
                <h5>{{item.name}}</h5>

                <div class="row">
                      <div class="col-sm-2">
                             <form  method='post'>
                                  {% csrf_token %}

                                  {% if item.done is True%}
                                      Done: <label class="checkbox-inline"><input type="checkbox" checked disabled data-toggle="toggle"></label>
                                  {% else %}
                                         {{form.as_p}}
                                  {% endif %}
                             </form>
                      </div>
                      <div class="col-sm-6">
                          {% if item.done is True%}
                            {{item.description}}
                          {% else %}
                            {{item.description}}
                          {% endif %}
                      </div>

                      <div class="col-sm-4">
                          {% if item.days_left == "Overdue!!!" %}
                            <p style="background-color:Tomato;">Status: {{item.days_left}}</p>
                          {% elif item.days_left == "Due today!" %}
                            <p style="background-color:Orange;">Status: {{item.days_left}}</p>
                          {% else %}
                            <p>Status: {{item.days_left}} days left</p>
                          {% endif%}
                      </div>

                </div>

            </li>
        {% endfor %}

    </ol>

    <button name="submit"  >Update my list</button></a>



{% endblock content %}